language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
      - ng lint
      name: check linter
    -
      script:
      - ng build --prod --base-href /GreenCityClient/ --aot=false --build-optimizer=false
      name: build app
    - stage: deploy
      script: skip
      provider: pages
      github_token: $TRAVIS_GH_TOKEN
      local_dir: dist/GreenCityClient
      on:
        branch: dev
