language: node_js
node_js:
  - "14"

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - dist

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
      - ng lint
      name: check linter
    -
      script:
      - ng build --prod --base-href /GreenCityClient/ --aot=false --build-optimizer=false
      name: build app
    -
      script:
      - echo 'Hi' && google-chrome --version
      name: test app
    - stage: deploy
      script: skip
      name: deploy on gh_pages
      if: branch IN (dev, master, pipeline)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_GH_TOKEN
        local_dir: dist/GreenCityClient
        on:
          branch: dev
